### ISSUE TITLE
meta: renaming pre-release migrations 

### ISSUE THREAD

**Issue by arthyn** [tloncorp/landscape#149]
We need to stand up the new agents, `%settings` and `%storage` while the others are still running aka `%settings-store` and `%s3-store`. This should add the relevant agent's code here along side the old version and start a migration of state between the two. 

I think it's ok if the migration is one shot instead of continuously staying up to date since these particular agents are relatively ephemeral. We'll release these likely nearly at the same time just with different kelvin support, so that once the actual kelvin upgrade happens the final state will be realized.

I had started the actual final state of the migration in #142 so you can use the contents of those files as the new agents.

**Comment by ashelkovnykov** [comment]
@arthyn Just pushed a commit which adds migration code. I got help from @philipcmonk with the design. I just tested it on a live moon, and it worked.

**Comment by ashelkovnykov** [comment]
Just for posterity, here were the commands I used to test:
```
.^(? %gu /(scot %p our)/settings-store/(scot %da now))
.^(? %gu /(scot %p our)/settings/(scot %da now))
=settings-types -build-file /=groups=/sur/settings/hoon
.^(data.settings-types %gx /(scot %p our)/settings-store/(scot %da now)/all/noun)
.^(data.settings-types %gx /(scot %p our)/settings/(scot %da now)/all/noun)

.^(? %gu /(scot %p our)/s3-store/(scot %da now))
.^(? %gu /(scot %p our)/storage/(scot %da now))
=storage-types -build-file /=groups=/sur/storage/hoon
.^(update.storage-types %gx /(scot %p our)/s3-store/(scot %da now)/credentials/noun)
.^(update.storage-types %gx /(scot %p our)/storage/(scot %da now)/credentials/noun)
.^(update.storage-types %gx /(scot %p our)/s3-store/(scot %da now)/configuration/noun)
.^(update.storage-types %gx /(scot %p our)/storage/(scot %da now)/configuration/noun)
```

**Comment by joemfb** [comment]
NB: the path for these `%gu` scries changes in 413.

**Comment by arthyn** [comment]
Fixed in my PR that I just put up
