### ISSUE TITLE
landscape: notify user on completion of long-running app install

### ISSUE THREAD

**Issue by dnbrwstr** [tloncorp/landscape#154]
We should send a notification when long running app installs complete in order to re-engage users if they've gotten distracted or lost interest in the interim. 

Implementation is up for grabs, but the heuristic for "long-running" could be any or all of:
- Installation has taken more than 1 minute
- Tab has entered background
- User has navigated away from dashboard

**Comment by patosullivan** [comment]
Note that this notification would only appear in Landscape (grid) itself.

**Comment by jamesacklin** [comment]
That's fine - we filter the native applications to only show notifications from the Talk desk.
