### ISSUE TITLE
Minified exception occurred

### ISSUE THREAD

**Issue by rhysmonkey** [tloncorp/landscape#59]
```
Error: Minified exception occurred
<img width="1209" alt="Screen Shot 2023-01-24 at 5 02 14 pm" src="https://user-images.githubusercontent.com/181897/214222710-85237bff-36b0-4097-915c-b7e8b92e5c02.png">

**Comment by jamesacklin** [comment]
@rhysmonkey What were you doing when this occurred? What browser are you using?

https://user-images.githubusercontent.com/181897/214222710-85237bff-36b0-4097-915c-b7e8b92e5c02.png

**Comment by rhysmonkey** [comment]
I was using Brave browser. I can't recall what I was doing. If you can't replicate, let me know, I will close the issue and if I encounter again will re-submit.
