### ISSUE TITLE
notifications: horizontal scroll on mobile

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape#60]
This was fixed in groups, but is busted in landscape.

See image.

![A87DFC73-79E3-4C3D-BCFE-FB4DBEBEA0D9](https://user-images.githubusercontent.com/441466/214852014-80a01980-7146-4114-8222-3ae9b0774754.jpeg)

I also wonder if landscape should even show chat notifications (maybe?) or if it should just be system/app level notifications? Probably they should just be grouped better like iOS lock screen does.

**Comment by jamesacklin** [comment]
Fixed in #52.
