### ISSUE TITLE
notifications: clicking on a notification should go to existing window if available

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape#61]
- Have talk open in an existing browser tab next to landscape
- Get notification for message in a talk thread in landscape
- Click notification
- Observe it open a new browser tab for talk and take ~10s to load

Ideally we'd just use the existing tab and go to the correct location (which would be way faster).
Also it'd be good if it didn't take so long to load even if talk isn't already open to switch too (but that's a separate issue).

As is, it's so slow I don't click them because it's faster to find it myself in the existing tab.

**Comment by galenwp** [comment]
I would also love this—but I think it's impossible for one tab to address another directly (unless the tab was opened by the tab that's trying to send an event).

This was one of the reasons for thinking about making a system tray widget for notifs.

**Comment by jamesacklin** [comment]
This is impossible with modern browsers.
