### ISSUE TITLE
notifications: mark all as read hangs with no spinner 

### ISSUE THREAD

**Issue by zalberico** [tloncorp/landscape#75]
- Have notifications in landscape
- Click Mark All as Read
- Observe nothing happen

The UI should show a spinner and then mark all notifications as read.

**Comment by jamesacklin** [comment]
Adding to this bug, especially given the advancements in #162 

https://github.com/tloncorp/landscape/assets/748181/8475cfef-3258-432c-82be-c9f0dd567a58

**Comment by jamesacklin** [comment]
Fixed in Landscape v1.10.0
