### ISSUE TITLE
landscape: incorrect profile color for 0-prefixed colors 

### ISSUE THREAD

**Issue by jamesacklin** [tloncorp/landscape#96]
When attempting to edit the sigil color field in the profile settings, it truncates leading zeroes and then pads out the last character. For example, I previously had my color set to 0000b2. After the upgrade, it had converted it to B22222. Attempting to change it back results in the same thing after a refresh. 1000b2 however works.

_Originally posted by @bazfum in https://github.com/tloncorp/landscape-apps/issues/1413_

**Comment by tomholford** [comment]
Could be the same issue as this?

https://github.com/tloncorp/landscape-apps/pull/1854

**Comment by jamesacklin** [comment]
It's the very same. We fixed it in Groups/Talk, just need to fix it in Landscape.

**Comment by rdp-studio** [comment]
I also encountered the same problem. My sigil color is not normally displayed in the upper right corner of Landscape.
