### ISSUE TITLE
Landscape notifications for mentions in groupchat don't link to group chat

### ISSUE THREAD

**Issue by ashelkovnykov** [tloncorp/landscape#98]
**Describe the bug, optionally with screenshots**
Clicking on a notification with a direct mention no longer takes you to the chat channel in which it happened, it just opens Groups in general.

**To Reproduce**
1. Go to Landscape
2. Open the notifications menu
3. Click on a notification from a chat where you were mentioned

**Expected behavior**
Clicking on a notification for a direct mention in a chat should take you to the chat channel in which it occurred.

**Additional context:**
- Ship type = planet
- Instance type = self-hosted
- Chromium-based browser on Pop!_OS 22.04
- I'm currently synced to `marnec`
  - Landscape hash: `0v1r.k849h.h6lvd.q252i.072d1.68q9d.ul6vk.rcqf1.93el2.umdg3.6v6ju`
  - Groups hash: `0v1r.pve3l.d4v4v.c127n.0dd4l.a8e0v.hug5c.5oru2.el3no.8bp4b.vivfu`

**Comment by patosullivan** [comment]
This appears to be fixed on master, we just haven't deployed recently, @jamesacklin
