### ISSUE TITLE
search/nav: double dialogs display incorrectly

### ISSUE THREAD

**Issue by arthyn** [tloncorp/landscape#99]
Since the radix-ui update our double dialogs started looking like this: 

<img width="1422" alt="Screen Shot 2023-02-25 at 5 43 41 PM" src="https://user-images.githubusercontent.com/5466421/221384709-ee74d43f-d465-44de-9032-02e746e06e69.png">

**Comment by jamesacklin** [comment]
@arthyn Complete?

**Comment by arthyn** [comment]
Yep
